### ISSUE TITLE
How to tune the parameter for better results?

### ISSUE THREAD

**Issue by StarsTesla** [iamNCJ/DiLightNet#3]
I run the demo on hf, it seems like the results prefer more specular? 
![img_v3_02d3_aca60eea-a132-47aa-9340-14536d8bc65g](https://github.com/user-attachments/assets/d259343d-b211-4a33-ac9f-f7e8d49459b9)
![img_v3_02d3_04ebc249-c3b7-43c5-9d8b-28ff867c3a8g](https://github.com/user-attachments/assets/a1cd5fe9-49b2-49dc-9e7e-b3ce208081c8)

**Comment by iamNCJ** [comment]
Hi, as a limitation of stable-diffusion-based methods, you need to tune your prompt, and other parameters including random seed, denoising step, cfg to find a better combination. In your scenario, lowering the cfg and trying other prompts should help.
