### ISSUE TITLE
Objaverse IDs

### ISSUE THREAD

**Issue by jmunkberg** [iamNCJ/DiLightNet#8]
Hello, 

Congrats to a very nice paper and thanks for sharing the code!

Could you share the Objaverse IDs for the four models used in Fig 14 in the supplemental material?

**Comment by iamNCJ** [comment]
Hi! Thanks for your interest. The Objaverse IDs for the four models are:

- 000-054/df63d81358944337af1add54f19821ad
- 000-020/f0aad4f64925479da3f607b186314eef
- 000-037/91e1e94421694a328b1e9e82aad16736
- 000-045/7f9164e6018c4ec7a3585bbf6e6d70df

They are chosen from the full test object id list, which can be check [here](https://github.com/iamNCJ/DiLightNet/blob/main/data_gen/assets/objaverse_fids/test_fids.txt).

**Comment by jmunkberg** [comment]
Many thanks!
